import { Tajawal } from 'next/font/google';
import { Rubik } from "next/font/google";
import "./globals.css";

    // For variable font (recommended for optimal performance)
    

    // If not using a variable font, specify weights
    const tajawal = Tajawal({
       weight: ['200', '300', '400', '500', '700', '800', '900'],
       subsets: ['arabic', 'latin'],
     });

     const rubik = Rubik({
  subsets: ["arabic"], // أو ["latin", "arabic"] إذا تحتاج الاثنين
  weight: ["300", "900"],
  
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={`${tajawal.variable} ${rubik.variable}`}  >
      <body >
        {children}
      </body>
    </html>
  );
}
