import { Tajawal , Handjet } from 'next/font/google';

import "./globals.css";
import RetroLoader from "@/components/RetroLoader";

    // For variable font (recommended for optimal performance)
    

    // If not using a variable font, specify weights
    const tajawal = Tajawal({
       weight: ['200', '300', '400', '500', '700', '800', '900'],
       subsets: ['arabic', 'latin'],
     });

    const handjet = Handjet({ subsets: ['latin'], variable: '--font-handjet' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={`${tajawal.variable} ${handjet.variable}`}  >
      <body >
        <RetroLoader>
        {children}
        </RetroLoader>
      </body>
    </html>
  );
}
